## config/authorities/concentrations.yml
terms:
  - id: Cell_Biology
    active: true
    term: Cell Biology
  - id: Organic_Chemistry
    active: true
    term: Organic Chemistry
  - id: American_History
    active: true
    term: American History