## config/authorities/departments.yml
terms:
  - id: art_sci
    active: true
    other: some info
    term: College of Arts and Sciences
    departments:
      - id: Biology
        active: true
      - id: Chemistry
        active: true
      - id: History
        active: true
      - id: example
        active: false
  - id: something
    active: true
    other: hi
    term: Grad School
    departments:
      - id: Gillings School of Public Health
        active: true
