terms:
  - id: African, African American & Diaspora Studies
    term: African, African American & Diaspora Studies
  - id: American Studies
    term: American Studies
  - id: Anthropology
    term: Anthropology
  - id: Applied Science
    term: Applied Science
  - id: Archaeology
    term: Archaeology
  - id: Art
    term: Art
  - id: Art History
    term: Art History
  - id: Asian Studies
    term: Asian Studies
  - id: Biology
    term: Biology
  - id: Biomedical Engineering
    term: Biomedical Engineering
  - id: Biostatistics
    term: Biostatistics
  - id: Business Administration
    term: Business Administration
  - id: Chemistry
    term: Chemistry
  - id: Classics
    term: Classics
  - id: Communication Studies
    term: Communication Studies
  - id: Comparative Literature
    term: Comparative Literature
  - id: Computer Science
    term: Computer Science
  - id: Creative Writing
    term: Creative Writing
  - id: Cultural Studies
    term: Cultural Studies
  - id: Dramatic Art
    term: Dramatic Art
  - id: Economics
    term: Economics
  - id: Education
    term: Education
  - id: English
    term: English
  - id: Environmental Health Sciences
    term: Environmental Health Sciences
  - id: Environmental Science
    term: Environmental Science
  - id: Environmental Studies
    term: Environmental Studies
  - id: Exercise & Sport Science
    term: Exercise & Sport Science
  - id: Folklore
    term: Folklore
  - id: Geography
    term: Geography
  - id: Geological Sciences
    term: Geological Sciences
  - id: Germanic & Slavic Languages & Literatures
    term: Germanic & Slavic Languages & Literatures
  - id: Global Studies
    term: Global Studies
  - id: Health Policy & Management
    term: Health Policy & Management
  - id: History
    term: History
  - id: Information & Library Science
    term: Information & Library Science
  - id: Interdisciplinary Health Communication
    term: Interdisciplinary Health Communication
  - id: Interdisciplinary Studies
    term: Interdisciplinary Studies
  - id: Journalism & Mass Communication
    term: Journalism & Mass Communication
  - id: Latin American Studies
    term: Latin American Studies
  - id: Linguistics
    term: Linguistics
  - id: Mathematical Decision Sciences
    term: Mathematical Decision Sciences
  - id: Mathematics
    term: Mathematics
  - id: Music
    term: Music
  - id: Nursing
    term: Nursing
  - id: Nutrition
    term: Nutrition
  - id: Peace, War, & Defense
    term: Peace, War, & Defense
  - id: Pharmacy
    term: Pharmacy
  - id: Philosophy
    term: Philosophy
  - id: Physics & Astronomy
    term: Physics & Astronomy
  - id: Political Science
    term: Political Science
  - id: Psychology
    term: Psychology
  - id: Public Health
    term: Public Health
  - id: Public Policy
    term: Public Policy
  - id: Religious Studies
    term: Religious Studies
  - id: Romance Languages
    term: Romance Languages
  - id: Sociology
    term: Sociology
  - id: Studio Art
    term: Studio Art
  - id: Women's & Gender Studies
    term: Women's & Gender Studies