terms:
  - id: WCAG 1.0 Level A
    term: WCAG 1.0 Level A
  - id: WCAG 1.0 Level AA
    term: WCAG 1.0 Level AA
  - id: WCAG 1.0 Level AAA
    term: WCAG 1.0 Level AAA
  - id: WCAG 2.0 Level A
    term: WCAG 2.0 Level A
  - id: WCAG 2.0 Level AA
    term: WCAG 2.0 Level AA
  - id: WCAG 2.0 Level AAA
    term: WCAG 2.0 Level AAA
  - id: WCAG 2.1 Level A
    term: WCAG 2.1 Level A
  - id: WCAG 2.1 Level AA
    term: WCAG 2.1 Level AA
  - id: WCAG 2.1 Level AAA
    term: WCAG 2.1 Level AAA
  - id: WCAG 2.2 Level A
    term: WCAG 2.2 Level A
  - id: WCAG 2.2 Level AA
    term: WCAG 2.2 Level AA
  - id: WCAG 2.2 Level AAA
    term: WCAG 2.2 Level AAA
