development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || 'http://solr:8983/solr/hydra-development' %>
test: &test
  adapter: solr
  url: <%= ENV['SOLR_TEST_URL'] || 'http://solr:8983/solr/hydra-test' %>
production:
  adapter: solr
  url: <%= ENV['SOLR_PRODUCTION_URL'] %>
