development:
  adapter: solr
  url: <%= ENV['SOLR_DEV_URL'] %>
  # url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:#{ENV.fetch('SOLR_DEVELOPMENT_PORT', 8983)}/solr/hydra-development" %>
test: &test
  adapter: solr
  url: <%= ENV['SOLR_TEST_URL'] %>
  # url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:#{ENV.fetch('SOLR_TEST_PORT', 8985)}/solr/hydra-test" %>
production:
  adapter: solr
  url: <%= ENV['SOLR_PRODUCTION_URL'] %>
