development:
  host: <% ENV['REDIS_HOST'] || 'localhost' %>
  port: 6379
test:
  host: <% ENV['REDIS_HOST'] || 'localhost' %>
  port: 6379
production:
  host: <% ENV['REDIS_HOST'] || 'localhost' %>
  port: 6379
