# This is a sample config file that points to a solr server for each environment
# This is a sample config file that points to a solr server for each environment
development:
  url: <%= ENV['SOLR_URL'] || 'http://solr:8983/solr/hydra-development' %>
test:
  url: <%= ENV['SOLR_TEST_URL'] || 'http://solr:8983/solr/hydra-test' %>
production:
  url: <%= ENV['SOLR_PRODUCTION_URL'] %>
  instance_dir: /opt/solr
