# This is a sample config file that points to a solr server for each environment
development:
  url: <%= ENV['SOLR_DEV_URL'] %>
  # url: http://127.0.0.1:<%= ENV['SOLR_TEST_PORT'] || 8983 %>/solr/hydra-development
test:
  url: <%= ENV['SOLR_TEST_URL'] %>
  # url: http://127.0.0.1:<%= ENV['SOLR_TEST_PORT'] || 8985 %>/solr/hydra-test
production:
  url: <%= ENV['SOLR_PRODUCTION_URL'] %>
  instance_dir: /opt/solr
