default: &default
  setup: tinymce_nav_safety # onChange event init
content_block:
  <<: *default
  menubar: false
  toolbar1: styleselect | bold italic | undo redo
  toolbar2: table | fullscreen | image
  plugins:
    - table
    - fullscreen
    - image
rich_text:
  menubar: false
  toolbar:
    - "undo redo | bold italic underline | alignleft aligncenter alignright | link | numlist bullist outdent indent | blockquote | code"
  plugins:
    - "link lists code"
  style_formats:
    - title: "Inline"
      items:
        - title: "Bold"
          inline: "b"
        - title: "Italic"
          inline: "i"
        - title: "Underline"
          inline: "u"
        - title: "Strikethrough"
          inline: "strike"
    - title: "Blocks"
      items:
        - title: "Paragraph"
          block: "p"
        - title: "Blockquote"
          block: "blockquote"
    - title: "Alignments"
      items:
        - title: "Left"
          block: ""
          classes: "align-left"
        - title: "Center"
          block: ""
          classes: "align-center"
        - title: "Right"
          block: ""
          classes: "align-right"
  setup: |
    function (editor) {
      const observer = new MutationObserver((mutationList) => {
        mutationList.forEach((mutation) => {
          if (mutation.type == "childList") {
            mutation.addedNodes.forEach((node) => {
              if (node instanceof Element) {
                if (node.matches(".tinymce")) {
    console.log('dean')
                  tinymce.init();
                }
              }
            });
          }
        });
      });
      observer.observe(document.body, { childList: true, subtree: true });

      editor.on('change', function () {
        tinymce.triggerSave();
        if (window.saveWorkControlInstance) {
          window.saveWorkControlInstance.validateMetadata();
        }
      });
    }

custom:
  <<: *default
